### ISSUE TITLE
Finder Toolbar Icon Size Is Too Small

### ISSUE THREAD

**Issue by fredngo** [Ji4n1ng/OpenInTerminal#106]
## What is the issue?

The icon for `openinterminal-lite` in the finder toolbar is too small.

## How does one reproduce the issue?

Drag the `OpenInTerminal-Lite.app` into the finder toolbar by holding down the `Cmd` key.

## Screenshots

<img width="677" alt="Screen Shot 2020-08-28 at 8 58 19 AM" src="https://user-images.githubusercontent.com/11791/91563563-15559b80-e90d-11ea-8543-6430c2bc3ecb.png">

## Debug information (Logs, OS, Hardware, Version, etc.)

* macOS High Sierra (10.13.6)

**Comment by Ji4n1ng** [comment]
This is really weird. Because this is the icon of the application, not the icon of the Finder extension. So you cannot guarantee that the app icon is the same size as the extension icon next to it. This bug is probably due to system reasons. You could try to manually replace icons as described in README of OpenInTerminal-Lite. If it still doesn't work, I can't think of any way to solve it.
