### ISSUE TITLE
Recognition of Alacritty Comes and Goes

### ISSUE THREAD

**Issue by w-r-z-k** [Ji4n1ng/OpenInTerminal#114]
## What is the issue?

Under "Installed Supported Applications" sometimes Alacritty appears then it disappears.

## How does one reproduce the issue?

Sometimes Alacritty appears in the "Default Terminal" dropdown but not in the "Installed Supported Applications" list. And sometimes the other way around.  It seems to change minute to minute.   The Content Menu Items also come and go.  Sometimes it says just "Copy Path" and sometimes all 3 options.  The app seems quite unstable.  

## Debug information (Logs, OS, Hardware, Version, etc.)

macOS Catalina 10.15.7

**Comment by Ji4n1ng** [comment]
Sorry for the late reply. This strange phenomenon may be because when judging whether you have installed Alacritty, OpenInTerminal usually goes to the `/Applications` and `~/Applications` directories to traverse all your applications. For performance, OpenInTerminal will stop searching when traversing some deep folders. So I guess there are deep folders in the two directories.
So, how to solve this problem. You can try to use the just released OpenInTerminal v2.3.0, which can directly add supported applications in the custom menu without having to determine whether the application is installed by the user.
