### ISSUE TITLE
Finder icon shows "Waiting ..." when clicking

### ISSUE THREAD

**Issue by emeidi** [Ji4n1ng/OpenInTerminal#148]
## What is the issue?
Added the OpenInTerminal.app icon to the Finder toolbar. When clicking the icon, it says "Waiting...", never showing "Open in Terminal" nor "Open in Atom"

## How does one reproduce the issue?
Enable the OpenInTerminal.app Finder Extensions under System Preferences. Add the OpenInTerminal.app icon to the Finder toolbar. Click the icon.

## Screenshots
<img width="105" alt="Screenshot 2021-05-09 at 22 19 46" src="https://user-images.githubusercontent.com/849604/117585872-0cac9a80-b115-11eb-8621-8960d2e0c329.png">

## Debug information (Logs, OS, Hardware, Version, etc.)
OpenInTerminal.app 2.3.3
macOS 11.3 Big Sur
MacBook Air (M1, 2020)

**Comment by Ji4n1ng** [comment]
Hi @emeidi , I have encountered the same situation. But I don't know why. Maybe it’s because there are too many apps running on my mac. It does not happen often and is easy to solve: 

1. Hold Option, right click on Finder, and select Relaunch.
2. If step 1 doesn't work, restart your Mac.

If you still have this problem, maybe you want to try OpenInTerminal-Lite and OpenInEditor-Lite.
