### ISSUE TITLE
Support for Warp

### ISSUE THREAD

**Issue by TopAlien** [Ji4n1ng/OpenInTerminal#173]
https://www.warp.dev/

**Comment by oncealong** [comment]
I tried "defaults write wang.jianing.app.OpenInTerminal-Lite LiteDefaultTerminal Warp",  OpenInTerminal-Lite can open `Warp`, but it doesn't support "Open in current directory"

**Comment by Cubik65536** [comment]
> I tried "defaults write wang.jianing.app.OpenInTerminal-Lite LiteDefaultTerminal Warp", OpenInTerminal-Lite can open `Warp`, but it doesn't support "Open in current directory", `Warp` always open the path when it last closed.
> I have no idea it is a bug of `OpenInTerminal` or `Warp`.

This is not a bug but a feature that needs to be implemented on both sides of `Warp` and `OpenInTerminal`.

`OpenInTerminal` uses an `open -a terminal` command to open the "not officially supported" terminals[^1]. But an `./path/to/directory` argument needs to be added to the command so the terminal would open in the wanted directory. And it will not work instantly because for now, `Warp` does not support the use of the `./path/to/directory` argument to launch the terminal with the directory open. (https://github.com/warpdotdev/Warp/discussions/612)

[^1]: https://github.com/Ji4n1ng/OpenInTerminal/blob/eed23120e02476ec9295ff8b1ab242b8ddd03ada/OpenInTerminalCore/ScriptManager.swift#L25

**Comment by Cubik65536** [comment]
/cc @Ji4n1ng 

In a [documentation of Warp](https://docs.warp.dev/features/integrations-and-plugins?_cio_id=eac40604a59a01e6c308#vscode), they said that the "Open in IDE" feature is implemented, and it is working. But I could not figure out how VSCode starts up a new terminal. So maybe this should be checked.

P.S. This function is **NOT** always working, sometimes Warp still starts up on the working directory, sometimes `~`. By comparison, `iTerm` starts always on the working directory.

**Comment by vnl** [comment]
@molvqingtai This worked partially for me, as, It opens two instances. One in root and the other in the current directory as it should.

**Comment by davay** [comment]
2 weeks ago Warp added public URIs  warpdotdev/Warp#612, might take a crack at it

**Comment by BC-M** [comment]
__Workaround__

Add this line to your `.zshrc' or `.bashrc' file, after the lines starting with `export PATH`:

```bash
[ "$TERM_PROGRAM" "==" "Apple_Terminal" ] && open -a Warp.app . && killall Terminal
```

**Comment by Ji4n1ng** [comment]
This is supported in [v2.3.7](https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/v2.3.7).

**Comment by insolor** [comment]
It seems that Warp is still not supported by the -lite version, although README says otherwise
