### ISSUE TITLE
[Question] Permission requirement for folders

### ISSUE THREAD

**Issue by chris-kenanga** [Ji4n1ng/OpenInTerminal#180]
Hi thanks for developing such an amazing tool.

I'm just wondering why there is a need to request permission for certain folder?

If I disable the permission what are the side effect or drawbacks?

Thanks,
Chris

**Comment by Ji4n1ng** [comment]
Hi, Chris. Currently, all fresh-installed mac apps are not allowed to access the user disk by default. However, OpenInTerminal needs to get which path is being accessed, which is all the information that OpenInTerminal needs. The most convenient way is to give `full disk access` permission to OpenInTerminal, your terminal apps, and editor apps in `Security & Privacy` of `Preferences`. If you disable the permission, OpenInTerminal will not work since it doesn't know which path you are accessing to open your terminal.
