### ISSUE TITLE
[FR] Alacritty support

### ISSUE THREAD

**Issue by 4cm4k1** [Ji4n1ng/OpenInTerminal#20]
## Summarize this feature
Alacritty (https://github.com/jwilm/alacritty) is a blazing fast terminal emulator app written in Rust, so my request is to support opening with that app in addition to Terminal, iTerm, and Hyper.

## Why should this feature be included?
Alacritty is becoming more and more popular.

## Additional information
N/A

**Comment by Ji4n1ng** [comment]
@4cm4k1 Good advice! The new version will consider this feature. 😀

**Comment by 4cm4k1** [comment]
Or perhaps the choice can be the user's. If there is a configuration file or a preference pane, then the user could specify the path of their preferred terminal app:

- `/Applications/Utilities/Terminal.app`
- `/Applications/iTerm2.app`
- `/Applications/Hyper.app`
- `/Applications/Alacritty.app`
- `/Applications/OtherTerminal.app`

Thanks! :D

**Comment by Ji4n1ng** [comment]
The script to open each terminal is not the same. This means that the program needs to be adapted for each terminal. Therefore, merely providing the path of the terminal is not enough. 

The version of the GUI (includes preference pane) is another program that will come in the near future. BTW, using a configuration file is a very good way when there is no GUI. Thank you for your kind advice!

**Comment by 4cm4k1** [comment]
Good to know! Thank you, @Ji4n1ng!

**Comment by Camji55** [comment]
@4cm4k1 @Ji4n1ng I am closing this ticket. It may be tracked in https://github.com/Ji4n1ng/OpenInTerminal/issues/22 from now on.

**Comment by Camji55** [comment]
@4cm4k1 Alacritty has been added into 0.4.1.

**Comment by Ji4n1ng** [comment]
@4cm4k1 You can set Alacritty as the default terminal:

```
defaults write wang.jianing.OpenInTerminal-Lite OIT_TerminalBundleIdentifier io.alacritty
```

Unfortunately it is only supported to open a new window now.

**Comment by 4cm4k1** [comment]
Thanks @Camji55 and @Ji4n1ng!

**Comment by 0rphee** [comment]
Hey @Ji4n1ng first of all, thanks for this amazing tool. 

Would it be possible that if there's one instance of Alacritty already running, OpenInTerminal would create a new window in the selected directory, instead of creating another Alacritty instance? 

looking at how the default configuration ([OpenInTerminalCore/ScriptManager.swift](https://github.com/Ji4n1ng/OpenInTerminal/blob/d51f29b04d2b7b1aa88845f26606012f4660b734/OpenInTerminalCore/ScriptManager.swift#L21)) for opening alacritty works, I don't think it would be very difficult to implement this.

I have an already working implementation for this as a bash script, though I don't really know how It would work with AppleScript (I understand that is what you're using...?) 


```bash
# Detects if Alacritty is running
# this doesnt work for whatever reason: pgrep -f "Alacritty" > /dev/null 2>&l
# a bit faster with yabai, but here's an alternative: ps uxww | grep -c -i -e alacritty

Query=$(yabai -m query --windows | grep -c -i -e "\"app\":\"Alacritty\"" | awk '{ if ($1>0) {print 1} else {print 0} }')
read a <<< $Query

if [ "$a" == "0" ]; then
    open -na Alacritty --args --working-directory ~/Documents/Dev # this last directory can be ignored, or customized 
    echo "awk result: $a \n USING OPEN" # message just for debugging purposes
else
    # Create a new window
    alacritty msg create-window --working-directory ~/Documents/Dev # this last directory can be ignored, or customized 
    echo "awk result: $a \n USING MSG"  # message just for debugging purposes
fi
```

**Comment by 0rphee** [comment]
Also, in another probably related note (please tell me if I should create another issue regarding this), do you have any plans for allowing other shell commands to be added as terminal(s)/editor(s)? 

(Excuse me if I'm assuming too much, I'm not fluent in Swift), but after taking a cursory look at the code, it seems not too far fetched to implement this. I ask for this functionality because I use a terminal-based editor (https://github.com/helix-editor/helix/) and it's sometimes kind of a hassle to open files/directories manually after coming from Finder, without having the option to just open it right from Finder.

And once again, thank you for your work!
