### ISSUE TITLE
Icon is too small compared to others

### ISSUE THREAD

**Issue by hubchau** [Ji4n1ng/OpenInTerminal#25]
## What is the issue?
I followed the README.md file to install the app, after dragging the icon to the toolbar, it showed up smaller than the other ones.

## How does one reproduce the issue?
Not sure

## Screenshots
![Screenshot](https://i.imgur.com/xDLlo5tl.png)

## Debug information (Logs, OS, Hardware, Version, etc.)
macOS 10.13.6
MBP 2017 15-inch
OpenInTerminal 0.4.0
I tried each available resolution, same result

**Comment by Ji4n1ng** [comment]
@hubchau I will look into this.

**Comment by hubchau** [comment]
@Ji4n1ng Thanks a lot. If you need anything (log, video, etc.) just let me know!

**Comment by Ji4n1ng** [comment]
@hubchau v0.9.0 has been released, which uses the Finder extension instead of the application in the Finder toolbar. This should fit nicely into the size of the Finder toolbar icon.

If you still want to use OpenInTerminal-Lite, I will provide different sizes of icons to fit macOS 10.13 in the next version. 😀
