### ISSUE TITLE
Expect the application don't to stay in the background

### ISSUE THREAD

**Issue by aoaoho** [Ji4n1ng/OpenInTerminal#32]
## Summarize this feature
Does the Finder extension have to rely on the application resident background to be used? I have seen it in some apps and can be used if the app is not running. For example: [FinderGo](https://github.com/onmyway133/FinderGo) and [Beyond Compare](https://www.scootersoftware.com/download.php)

**Comment by Ji4n1ng** [comment]
@aoaoho Thank you for your good advice. 

Because `FinderExtension` is sandboxed, the extension of `OpenInTerminal` cannot be run independently. So the ideas provided by `FinderGo` have inspired me.

Some of the features of `OpenInTerminal` are based on ScriptingBridge, whereas `FinderGo` is based entirely on AppleScript. The former is faster, although the difference is small.

The functionality provided by `FinderGo` is simpler than `OpenInTerminal`. OpenInTerminal needs to be changed very much if it is based entirely on AppleScript. And it is difficult to say whether it can achieve the current features.

So if OpenInTerminal can achieve the current features based entirely on AppleScript, then it is very good that FinderExtension supports stand-alone running. If not, it will not be supported.

Thank you again for your good advice. 😀

**Comment by aoaoho** [comment]
@Ji4n1ng 👍 Thank you for your detailed reply, I understand the reason. Looking forward to your research results. 😄

**Comment by gingerbeardman** [comment]
Thanks for this app!

Let me know if you require help with the AppleScript.

**Comment by Ji4n1ng** [comment]
@gingerbeardman You are really nice. Thank you very much!

**Comment by Ji4n1ng** [comment]
@aoaoho Sorry to reply you now. Some features of OpenInTerminal are not implemented, if it's based entirely on AppleScript, such as keyboard shortcuts. So OpenInTerminal must stay in the background. But it's such a very small application that we can ignore it. And you can use OpenInTerminal-Lite and OpenInEditor-Lite. 😀
