### ISSUE TITLE
Automatically switch icons when switching from/to Dark mode

### ISSUE THREAD

**Issue by Lapsusone** [Ji4n1ng/OpenInTerminal#38]
# OpenInTerminal-Lite
## Summarize this feature
Change Finder extension icon dynamically when switching from dark mode to light mode
## Why should this feature be included?
It makes no sense to have to manually replace the icon if we're set to use Dark mode only at certain times of the day
## Additional information

**Comment by Ji4n1ng** [comment]
Hi @Lapsusone . As for `OpenInTerminal-Lite`, the icon in Finder Toolbar is app icon not Finder extension icon. And I have not found a API to change the app icon (If you have any good idea, please let me know). Therefore, it is not currently possible to replace it automatically based on Dark mode. 
As for `OpenInTerminal`, the icon of it in Finder Toolbar is Finder extension icon. It can change automatically when switching between dark mode and light mode. So you can try to use `OpenInTerminal`.

**Comment by Camji55** [comment]
Changing this icon programmatically is currently not possible on macOS. Fingers crossed we get an API to do so at WWDC.

**Comment by Lapsusone** [comment]
Thank you for your replies. Hopefully this gets announced in the close-coming macOS public beta. In the meantime you can close this issue if you feel it’s appropriate.

**Comment by Camji55** [comment]
I'll add it to the todo list in the README and close this out.

Thanks for bringing this up @Lapsusone!

**Comment by melgu** [comment]
> Hi @Lapsusone . As for `OpenInTerminal-Lite`, the icon in Finder Toolbar is app icon not Finder extension icon. And I have not found a API to change the app icon (If you have any good idea, please let me know). Therefore, it is not currently possible to replace it automatically based on Dark mode.
> As for `OpenInTerminal`, the icon of it in Finder Toolbar is Finder extension icon. It can change automatically when switching between dark mode and light mode. So you can try to use `OpenInTerminal`.

Couldn't you make the lite version a Finder extension as well? Or wouldn't that work with one click?

**Comment by Ji4n1ng** [comment]
Hi @melgu . To make it clear why the lite version will not support Finder extension, I need to explain the implementation mechanism of OpenInTerminal.
There are two ways to achieve "open in terminal". The first is using ScriptingBridge. It's faster and `OpenInTerminal-Lite` and actions of `OpenInTerminal` in status bar menu are based on this way. Its disadvantage is that applications which use ScriptingBridge to access user's directory cannot be sandboxed. Therefore, this way cannot be applied to Finder extension which must be sandboxed. The second is using AppleScript. Currently Finder extension of `OpenInTerminal` is completely dependent on AppleScript in order to run independently. In the old version, OpenInTerminal must always be in the background to receive messages from Finder extension.
(I know there are apps that is sandboxed and can achieve the same effect. But I don't know how it works. If anyone can tell me, that would be great.)

Returning to your question, OpenInTerminal-Lite won't support Finder extension. It is designed to be lighter and faster. To meet the needs of others, OpenInTerminal was split into a normal version and a lite version a few months ago. So you have to choose between the two. 😂 Maybe in the future OpenInTerminal will change the way to use Finder extension, such as using 3 single buttons instead of integrating 3 actions into a menu.

**Comment by melgu** [comment]
@Ji4n1ng Thanks for the elaborate explanation!
