### ISSUE TITLE
hide icon in macOS menu bar

### ISSUE THREAD

**Issue by livc** [Ji4n1ng/OpenInTerminal#45]
## Summarize this feature
We could hide the icon in the macOS menu bar.

## Why should this feature be included?
The icon should be hidden if users want.

**Comment by Ji4n1ng** [comment]
@livc Good suggestion! Next version will support this feature.

**Comment by livc** [comment]
@Ji4n1ng Thanks, could it be updated automatically?

**Comment by Ji4n1ng** [comment]
@livc Short answer: no.

This is a very small and (most of the time) stable application. There are no requirements for frequent updates. And `Homebrew` is currently being used to manage updates. So when you sometimes remember to update brew cask, it will be updated. Since it is a tool, just use it and forget that it is an application. 😀

**Comment by Ji4n1ng** [comment]
@livc OpenInTerminal v2.0.2 has supported this feature.

https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/2.0.2

**Comment by livc** [comment]
@Ji4n1ng Can I `brew cask upgrade openinterminal` now? Seems failed.

**Comment by Ji4n1ng** [comment]
The current version in Homebrew is the old version. Homebrew takes time to review. So you can update it in a few days. I will inform you in this issue after the update.

**Comment by livc** [comment]
ok, thanks.

**Comment by Ji4n1ng** [comment]
@livc The version in Homebrew has updated to the latest version 2.0.3
